server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  # ====== Spring Cloud Consul for Service Discovery ======
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true #优先使用服务ip进行注册
        #service-name:服务8001以对应spring-application-name的名字入住到consul中
        service-name: ${spring.application.name}
