server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #========= applicationName + druid-mysql8 dirver ========
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: lining123
  #profiles:
    #active: dev #多环境配置加载内容dev/prod，不写就是默认default配置

# ======= mybatis ======
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.cloud.entities
  configuration:
    map-underscore-to-camel-case: true

# ======= seata ======
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: SEATA_GROUP
      application: seata-server
  tx-service-group: default_tx_group #事务组，由它获得TC服务的集群名称
  service:
    vgroup-mapping: #点击源码分析
      default_tx_group: default #事务组与TC服务集群的映射关系
  data-source-proxy-mode: AT #默认AT，不写也可以

#seata日志级别-info详细
logging:
  level:
    io:
      seata: info