server:
  port: 9528
spring:
  application:
    name: cloud-alibaba-sentinel-gateway #sentinel+gateway整合Case
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    gateway:
      routes:
        - id: pay_routh1                 # 路由ID, 要求唯一
          uri: http://localhost:9001 #lb://cloud-payment-service # 匹配后提供服务的地址
          predicates:
            - Path=/pay/**    # 断言, 路径匹配后进行路由